MobileStore/Controllers/Home_Controller.cs
using MobileStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileStore.Controllers
{
    public class Home_Controller : Controller
    {
        MobileStoreEntities _db = new MobileStoreEntities();

        // GET: Home_
        public ActionResult Index()
        {
            return View(_db.Products.ToList());
        }
    }
}

MobileStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MobileStore/Views/Shared/_MainLayout.cshtml
@{
    ViewBag.Title = "_MainLayout";
}

<!DOCTYPE HTML>
<html>
<head>
    <title>Mobilestore Website Template | Home :: W3layouts</title>
    <link href="~/Asset/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <meta name="keywords" content="Mobilestore iphone web template, Android web template, Smartphone web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <link href='//fonts.googleapis.com/css?family=Londrina+Solid|Coda+Caption:800|Open+Sans' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Asset/css/responsiveslides.css">
    <script src="~/Asset/js/jquery.min.js"></script>
    <script src="~/Asset/js/responsiveslides.min.js"></script>
    <script>
        // You can also use "$(window).load(function() {"
        $(function () {

            // Slideshow 1
            $("#slider1").responsiveSlides({
                maxwidth: 1600,
                speed: 600
            });
        });
    </script>
</head>
<body>
    <div class="wrap">
        <!----start-Header---->
        <div class="header">
            <div class="search-bar">
                <form>
                    <input type="text"><input type="submit" value="Search" />
                </form>
            </div>
            <div class="clear"> </div>
            <div class="header-top-nav">
                <ul>
                    <li><a href="#">Register</a></li>
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Delivery</a></li>
                    <li><a href="#">Checkout</a></li>
                    <li><a href="#">My account</a></li>
                    <li><a href="#"><span>shopping cart&nbsp;&nbsp;: </span></a><label> &nbsp;noitems</label></li>
                    <li>
                        <a href="@Url.Action("ShowToCart", "ShoppingCart")">
                            <img src="@Url.Content("~/Asset/images/cart-icon.png")" style="height:50px; width: 50px; padding-top: 10px" />
                        </a>
                        @Html.Action("BagCart", "ShoppingCart")
                    </li>
                </ul>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <div class="clear"> </div>
    <div class="top-header">
        <div class="wrap">
            <!----start-logo---->
            <div class="logo">
                <a href="@Url.Action("Index", "Home_")"><img src="~/Asset/images/logo.png" title="logo" /></a>
            </div>
            <!----end-logo---->
            <!----start-top-nav---->
            <div class="top-nav">
                <ul>
                    @*<li><a href="index.html">Home</a></li>*@
                    <li>@Html.ActionLink("Home", "Index", "Home_")</li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="store.html">Store</a></li>
                    <li><a href="store.html">Featured</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <!----End-top-nav---->
    <!----End-Header---->
    <!--start-image-slider---->
    @RenderBody()
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h3>Our Info</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h3>Latest-News</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h3>Store Location</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <h3>Order-online</h3>
                    <p>080-1234-56789</p>
                    <p>080-1234-56780</p>
                </div>
                <div class="col_1_of_4 span_1_of_4 footer-lastgrid">
                    <h3>News-Letter</h3>
                    <form>
                        <input type="text"><input type="submit" value="go" />
                    </form>
                    <h3>Follow Us:</h3>
                    <ul>
                        <li><a href="#"><img src="~/Asset/images/twitter.png" title="twitter" />Twitter</a></li>
                        <li><a href="#"><img src="~/Asset/images/facebook.png" title="Facebook" />Facebook</a></li>
                        <li><a href="#"><img src="~/Asset/images/rss.png" title="Rss" />Rss</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="clear"> </div>
        <div class="wrap">
            <div class="copy-right">
                <p>&copy; 2013 Mobile Store. All Rights Reserved | Design by  <a href="http://w3layouts.com/">W3Layouts</a></p>
            </div>
        </div>
    </div>
</body>
</html>